### ISSUE TITLE
All the Activity icons turn white

### ISSUE THREAD

**Issue by Feboli** [Kunzisoft/Android-SwitchDateTimePicker#13]
When the date change, the icons in the listview turn white

**Comment by J-Jamet** [comment]
Yeh sorry, it's bug from Styles. I'm making a new version that will come out today or tomorrow. 
When you say ListView, are you talking about a list you created for the current activity?

**Comment by Feboli** [comment]
OK thanks.....yes I have created a simple listview which updates imageview by date choice

**Comment by J-Jamet** [comment]
It's normally OK with 1.5 version! ;) Tell me if it's good for you!

**Comment by Feboli** [comment]
It's good, now it works.....
There is another little thing that i verified: sometimes when I rotate the display, for example from portrait to landscape, the calendar layout does not update.
I agree with you, it is a bit slow, but it's a good library.
