### ISSUE TITLE
Hours not appearing

### ISSUE THREAD

**Issue by MuhamedFathy** [Kunzisoft/Android-SwitchDateTimePicker#15]
Hours not appearing on SDK 17, See screenshot:

<img width="612" alt="screen shot 2017-02-21 at 20 17 51" src="https://cloud.githubusercontent.com/assets/4931115/23178427/0ac2c122-f873-11e6-8f51-6160eb44a653.png">

Also check the RTL UI

<img width="612" alt="screen shot 2017-02-21 at 20 22 49" src="https://cloud.githubusercontent.com/assets/4931115/23178582/a4c8bb0a-f873-11e6-9589-bd8a87b68c67.png">

on SDK 24 UI working good, but the arrows the same as above screenshot.

**Comment by J-Jamet** [comment]
Thanks for the reply. 
I think this is a theme issue. For the arrows, it comes from the library included, I'll try to settle that.

**Comment by J-Jamet** [comment]
So I'll do a better management of RTL (Right to left) in the next version. I'll do the best! ;)

**Comment by MuhamedFathy** [comment]
Great, Thanks a lot.

**Comment by J-Jamet** [comment]
1.6 version now use RTL elements, unfortunately, arrow in calendar can't be change for the moment. It's a bug link to https://github.com/prolificinteractive/material-calendarview/issues/545

**Comment by khalid-mahmood** [comment]
@J-Jamet  Hours not showing , double digits not showing like 10,11,12

**Comment by MuhamedFathy** [comment]
After version 1.6 the numbers still cutting from down, Also the years appear with English numbers not Hindi.

![screenshot_1496141833](https://cloud.githubusercontent.com/assets/4931115/26580286/b7978b92-4537-11e7-9805-2dffcd2bb171.png)

**Comment by J-Jamet** [comment]
Thanks for the image, I will try to solve this.

**Comment by MuhamedFathy** [comment]
Also issue appear in 7-inch tablet Android v4.3

![screenshot_2017-07-05-14-37-46](https://user-images.githubusercontent.com/19631927/27864572-6f287604-618f-11e7-808b-80cc9020d8db.png)

**Comment by MuhamedFathy** [comment]
Tablet in landscape mode

English [LTR]

![device-2017-07-17-183022](https://user-images.githubusercontent.com/4931115/28278794-a7b64756-6b1e-11e7-89c3-ff332e49d37c.png)


Arabic [RTL]

![device-2017-07-17-183543](https://user-images.githubusercontent.com/4931115/28278861-dd303acc-6b1e-11e7-9a1f-efea524e7ba5.png)

**Comment by J-Jamet** [comment]
Thanks for the return, however I do not have much time for me right now. So sorry, I'll watch when my calendar is calmer, but you can advance the dev and make a pull request if you solve the issue before me. ;)

**Comment by J-Jamet** [comment]
It's not perfect, but better in 1.8 version.
