### ISSUE TITLE
conflict with manifest merger

### ISSUE THREAD

**Issue by luna-vulpo** [Kunzisoft/Android-SwitchDateTimePicker#16]
I get below error. It seems that in your manifest.
I workaround problem by adding what is in suggestion, but I think that your lib shouldn't make such conflict

```
Error:Execution failed for task ':app:processFullDebugManifest'.
> Manifest merger failed : Attribute application@label value=(Name o my app) from AndroidManifest.xml:12:9-35
  	is also present at [com.github.Kunzisoft:Android-SwitchDateTimePicker:1.5] AndroidManifest.xml:13:9-41 value=(@string/app_name).
  	Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:8:5-54:19 to override.
```

**Comment by J-Jamet** [comment]
As I use JitPack, it automatically creates the API and the sample that contains the application name resource is added. I will manually enter the modules to integrate when I go with JCenter or MavenCentral. Thank you for the feedback. :)

**Comment by J-Jamet** [comment]
I have change resource for sample. No more "replace" needed.
