### ISSUE TITLE
Days of the calendar

### ISSUE THREAD

**Issue by Feboli** [Kunzisoft/Android-SwitchDateTimePicker#17]
In API Level 22 the days in the calendar are not complete, like image.
For example, in the screenshot, the ultimate day is 25, are missing 26, 27, etc.....
Thanks in advance.

![cal](https://cloud.githubusercontent.com/assets/12711886/24105417/1c08cae0-0d85-11e7-9519-b28b86425513.png)

**Comment by J-Jamet** [comment]
You're right, I'll change that in the next version. ;)

**Comment by J-Jamet** [comment]
Hi, can you tell me what are the size of screen and resolution. The model of the phone or the emulator would be even better. Thank you

**Comment by Feboli** [comment]
The problems have occurred in these emulators:
Nexus 4 - 768x1280 - API 24
Nexus 4 - 768x1280 - API 22
Nexus 9 - 2048x1536 - API 23 (tablet)

**Comment by J-Jamet** [comment]
Thank you for your return, I am modifying the dimensions of the calendars for these resolutions. I hope to put the new version online soon.

**Comment by J-Jamet** [comment]
Normally ok in version 1.6, tell me if it's good for you ! ;)

**Comment by Feboli** [comment]
Ok now it works well
Thank you
