### ISSUE TITLE
how to change the color for other items apart from title

### ISSUE THREAD

**Issue by laurentyew** [Kunzisoft/Android-SwitchDateTimePicker#2]
using <color name="dateTimeColorAccent"> only change the title color for me. how can i change the color for the other items ?

**Comment by laurentyew** [comment]
the textcolor as well. thanks!

**Comment by J-Jamet** [comment]
Hello, I plan to change the color selection in the next version. I do it today. ;)

**Comment by J-Jamet** [comment]
It's done in v1.0-rc.4. I'll redo the DatePicker and TimePicker in the future for better customization. New version is OK for you ?

**Comment by laurentyew** [comment]
awesome , sir , appreciate it a lot!

**Comment by laurentyew** [comment]
hi sir,

i tried to change the color of the pickers but somehow they are still green and white no matter how i change. i created my own theme but still it doesn't change
![screenshot_20161104-103617](https://cloud.githubusercontent.com/assets/5634301/19992672/df8d8e04-a27a-11e6-8885-d666698a8d6f.png)

**Comment by laurentyew** [comment]
my problem. manage to get it working

**Comment by J-Jamet** [comment]
TimePicker and DatePicker views are managed by the Android system. I'll create my own views soon, but for now we must change the common value of the theme with colorAccent. :/ I tried to do that this weekend.

**Comment by J-Jamet** [comment]
I created a new branch for custom views. We can change the styles of all elements, it will be over in a few days. :)

**Comment by J-Jamet** [comment]
You can now apply the style you want to most components :)

**Comment by laurentyew** [comment]
thanks for the effort!  appreciate it . but somehow it seems like it does not get overwritten

here is my style
![image](https://cloud.githubusercontent.com/assets/5634301/21471645/87016b1a-caf3-11e6-8438-5052aa569b17.png)

**Comment by laurentyew** [comment]
but the color did not change. 

i have 2 button below. but they cannot be seen because text color is white. it seems to be taking the color from my custom theme with textcolor attribute.  Any way to overwrite that? 

![image](https://cloud.githubusercontent.com/assets/5634301/21471663/fe90010a-caf3-11e6-8bda-b1eab5f45083.png)

**Comment by J-Jamet** [comment]
To overwrite button text color, you can redefine a style only for activity who contains Dialog or make a dark theme. These are the first ways... I have to change that but no time.

**Comment by laurentyew** [comment]
i think the issue happens with nougat , as i have tried with textcolor and it doesn't work.

this is a workaround

  <style name="dialog" parent="Base.Theme.AppCompat.Light.Dialog.Alert">
               <item name="buttonBarButtonStyle">@style/DialogButtonStyle</item>
    </style>

    <style name="DialogButtonStyle" parent="@style/Widget.AppCompat.Button.ButtonBar.AlertDialog">
        <item name="android:textColor">@color/black</item>
    </style>

**Comment by J-Jamet** [comment]
Hi, for change text color of button's dialog, you need to change
`colorAccent` attribute in your style.

Example :

    <style name="DialogActivityStyle" parent="Theme.AppCompat.Light.DarkActionBar">
        <item name="colorAccent">@color/colorAccent</item>
        <item name="android:colorAccent">@color/colorAccent</item> 
    </style>
