### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by sluedecke** [Kunzisoft/Android-SwitchDateTimePicker#21]
I like this library a lot, but I am unsure how it it licensed.  Can you please clarify it by adding a license file?

Thanks a lot in advance!

**Comment by J-Jamet** [comment]
Of course, the program is licensed under Apache 2. You can use it as you want, for open source or commercial software. But a donation would be really appreciated, I spend a lot of time adding features and create open source softwares for everyone. ;)

**Comment by sluedecke** [comment]
Thanks for clarifying it, I will donate (give me some time to actually do it) since I appreciate open source and the work behind it in general and your work specifically :)
