### ISSUE TITLE
nougat - button color not visible 

### ISSUE THREAD

**Issue by vandanabpatel** [Kunzisoft/Android-SwitchDateTimePicker#25]
<style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
        
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>

        
        <item name="android:actionBarSize">@dimen/actionbar_height</item>
        <item name="windowActionBar">false</item>
        <item name="windowNoTitle">true</item>
        <item name="android:windowLightStatusBar">false</item>
        <item name="windowActionModeOverlay">true</item>

        <item name="android:editTextStyle">@style/ProEditTextRound</item>
        <item name="android:buttonStyle">@style/ProButton</item>
        <item name="android:textAppearance">@style/ProTextView_gray</item>
    </style>

**Comment by J-Jamet** [comment]
??? What does it mean ? The library has been tested and runs on Nougat.
