### ISSUE TITLE
24 Hours mode - Minutes selection

### ISSUE THREAD

**Issue by mdenissov** [Kunzisoft/Android-SwitchDateTimePicker#29]
1. Open dateTime dialog
2. Select date
3. Click on minutes 

Expected screen - minutes selection
Actual screen - hours selection

When touch on the clock face the UI not changed but minutes values changes.

**Comment by J-Jamet** [comment]
Thanks for your return. I will look at how to change the view to resolve the bug.

**Comment by nitin3210** [comment]
Any Updates?

**Comment by jmbbaker** [comment]
Hello, we are experiencing the same issue.  It appears to happen when you click the minutes of the time in the upper left corner. It will show the Hour picker.  If you spin (drag) the hour, it actually changes the minutes.  If you click the time hour, then the time minutes again, it shows the minutes properly.

**Comment by nitin3210** [comment]
I have solved this by my own. But you need to add this library as module. and also add feature open time picker when user select the date. I will send you the code. But don't know how to merge this code in that library

**Comment by jmbbaker** [comment]
Wonderful. Can you put the code in Google Drive or somewhere similar and send a link to grab it?

**Comment by nitin3210** [comment]
Hi Sorry for late response, You can take code from here
https://github.com/nitin3210/Android-SwitchDateTimePicker and I also send the pull request hope this will merge in original code soon.

**Comment by J-Jamet** [comment]
I'm on it, (I'm testing), I'll create a new version 1.9 for JitPack with only your mod for a fast delivery. (
And I will release another version later with more features.)
