### ISSUE TITLE
AM/PM Issue

### ISSUE THREAD

**Issue by dkalian** [Kunzisoft/Android-SwitchDateTimePicker#30]
AM/PM indicator displays incorrectlly on 720x1280 screens

![image](https://user-images.githubusercontent.com/2602322/32169190-8460a6ac-bd80-11e7-9a44-4e48f65b550e.png)

**Comment by J-Jamet** [comment]
Thank you for the feedback. 
It is possible to temporarily change the style to decrease the size of the hour, until the bug is corrected in the next version.

**Comment by nitin3210** [comment]
Any Updates

**Comment by J-Jamet** [comment]
I'll take care of it when I have time. I know it's a bit long, I apologize but I have a lot of other projects. I work according to priorities. Do not hesitate to tell me if you have constraints and a high priority.

**Comment by nitin3210** [comment]
I resolved both the issue. In a hacky way but it works like a charm. and also add a feature open Timepicker after selecting the date. But i don't know the process of merge in your code.

**Comment by J-Jamet** [comment]
You have to make a pull request. And after validation it is integrated in the main code. https://help.github.com/articles/creating-a-pull-request/

**Comment by nitin3210** [comment]
Thank you. I will send you the pull request.

**Comment by J-Jamet** [comment]
It's done in version 1.9
