### ISSUE TITLE
How to change ampmcircleview color ? 

### ISSUE THREAD

**Issue by blancnoir-d** [Kunzisoft/Android-SwitchDateTimePicker#34]
applied default style and custom style 
but only not changed ampm click event color.
background, selectbackground, textcolor.

`<item` `name="timeAmPmBackgroundColor">#C746FB</item>`
`<item` `name="timeAmPmSelectBackgroundColor">#32b3e3</item>`
`<item` `name="timeAmPmTextColor">#C746FB</item>`

how to change color?

**Comment by J-Jamet** [comment]
I'll solve the problem in the next version.

**Comment by J-Jamet** [comment]
Fixed in version 2.0
