### ISSUE TITLE
Custom style has no effect

### ISSUE THREAD

**Issue by zukopvd** [Kunzisoft/Android-SwitchDateTimePicker#35]
version 1.9 Android 7.0

Even using your sample app adding and changing of UI items style has no any effect - it's always default. 

(AppCompat used as the base theme in your and my code as well)

**Comment by p3na** [comment]
@zukopvd I guess, you probably need to create a new `styles.xml` in `res/values-v21` and overwrite the style attributes there for devices running Android API versions >21 (_5.0 Lollipop_), older API versions will use the "default" `styles.xml`.

**Comment by J-Jamet** [comment]
There are problems with the themes I must refactor the code, I'll try to do it for version 2.0

**Comment by J-Jamet** [comment]
No need to use style in v21 since version 2.0
