### ISSUE TITLE
Possibility to change the setting of the PM and AM circles

### ISSUE THREAD

**Issue by andyunoone** [Kunzisoft/Android-SwitchDateTimePicker#36]
Is it possible to change the display order of the PM and AM circles?
Setting in external AM and internal PM?
Thank you

**Comment by J-Jamet** [comment]
Currently no but why not in the next release!

**Comment by J-Jamet** [comment]
You can do it since version 2.0 with `dateTimeFragment.setHighlightAMPMSelection(true);`

**Comment by andyunoone** [comment]
Hello, thanks for your attention but there are two problems with the new 2.0 release, as photos now the year is no longer displayed correctly and setting:
dateTimeFragment.setHighlightAMPMSelection(true);
the crown of the AM is always inside the crown of the PM
and not externally.

Thanks for collaboration






Andrea Molinari
ANDROID DEVELOPER
 
UNOONE Srl

Via A. Masina, 9
00153 ROMA
 
Tel dir: +39 06 58503218
Fax: +39 06 5816585

P.IVA: 13786571003

E-mail: a.molinari@unoone.it <mailto:a.molinari@crossdata.it>

Pensa all’ambiente! Stampa questa e-mail solo se veramente necessario!
Ai sensi del Dlgs 196/2003 e successive modifiche/integrazioni si precisa che le informazioni  contenute nel presente messaggio, e negli eventuali allegati, sono riservate e per uso esclusivo del destinatario. Pertanto è vietata la copia, la diffusione e la rivelazione anche parziale dei dati in esso contenuti alle persone non autorizzate dal medesimo. Chiunque lo ricevesse per errore è pregato di restituirlo al mittente e di distruggere il contenuto.
