### ISSUE TITLE
i can't set minimum date 

### ISSUE THREAD

**Issue by dominicg666** [Kunzisoft/Android-SwitchDateTimePicker#42]
Calendar calendar = Calendar.getInstance();
        Integer year = calendar.get(Calendar.YEAR);
        Integer month = calendar.get(Calendar.YEAR);
        Integer day = calendar.get(Calendar.YEAR);
        checkinDatePicker.setText(Calendar.YEAR+"");

        // Assign unmodifiable values
        dateTimeFragment.set24HoursMode(false);
        dateTimeFragment.setHighlightAMPMSelection(false);
        dateTimeFragment.setMinimumDateTime(new GregorianCalendar(year, Calendar.MONTH, Calendar.DAY_OF_MONTH).getTime());

**Comment by J-Jamet** [comment]
Read the doc to create a good Calendar, here you use the labels of the month and the day and you create all your variables with the year...
