### ISSUE TITLE
i can not be set minimum time

### ISSUE THREAD

**Issue by dominicg666** [Kunzisoft/Android-SwitchDateTimePicker#43]
hi, i need to minimum time set, please help me

**Comment by J-Jamet** [comment]
It is not yet implemented and I have no time to do it, you can do a pull request for this. If you want absolutely and quickly this feature, I take it for a mission and not for a particular project. You can send me an email at jeremy.jamet@kunzisoft.com for modalities. linked to #https://github.com/Kunzisoft/Android-SwitchDateTimePicker/issues/33

**Comment by dominicg666** [comment]
can you send to mail this particular module? my mail id **dominicg666@gmail.com**
