### ISSUE TITLE
set default date on click as todays date currently showing december 2017

### ISSUE THREAD

**Issue by himanshu-infield** [Kunzisoft/Android-SwitchDateTimePicker#44]

**Comment by himanshu-infield** [comment]
its working fine now need to set  dateTimeFragment.setDefaultDateTime(myCalendar.getTime()); while initialisation.

Another problem i am getting is when i click a view quickly it gives exception Fragment already added.Do you know any solution for this.

**Comment by yajra** [comment]
@himanshu-infield having the same issue, were you able to figure out a solution?

**Comment by yajra** [comment]
Ok, I think I found a way for fragment added concern:

```
if (dateTimeFragment.isAdded) {
  return
}
dateTimeFragment.show(...)
```

**Comment by J-Jamet** [comment]
These are not really bugs, you can initialize the default date with the one you want and otherwise it's normal fragment management. ;)
