### ISSUE TITLE
warn: ignoring element 'g' with unknown namespace

### ISSUE THREAD

**Issue by dineshmm23** [Kunzisoft/Android-SwitchDateTimePicker#49]
Caused by: java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed

> C:\Users\%username%\.gradle\caches\transforms-1\files-1.1\jetified-Android-SwitchDateTimePicker-2.0.aar\3a84e72fe4257cd5f213e12017fa551a\res\values\values.xml:35:5-89: AAPT: warn: ignoring element 'g' with unknown namespace 'http://schemas.android.com/tools'.

Causing errors in androidx  after merging values. Unable to build due to some  error in values.xml
<string name="deleted_key"><ns1:g example="4" id="key">%1$s</ns1:g> deleted</string>

**Comment by dineshmm23** [comment]
Problem caused: Due to conflict(maybe) of  ns1:g
Fixed : removed  google material library

I hope this might be the cause

**Comment by J-Jamet** [comment]
Ok, I have fix this issue in development.

**Comment by Ahmed1011** [comment]
Hi I have same error, can I know how to fix it. Thanks
