### ISSUE TITLE
Possible to set a min and/or max date and/or time?

### ISSUE THREAD

**Issue by Rainer-Lang** [Kunzisoft/Android-SwitchDateTimePicker#5]

**Comment by J-Jamet** [comment]
I have bugs on the minimum and maximum years. I look at the same time for this request but priority to bugs! ;)

**Comment by Rainer-Lang** [comment]
@J-Jamet I completely understand you with "bugs". ;)
Please don't feel in any matter rushed.

**Comment by J-Jamet** [comment]
Same as issue #11, I close this one. You can set a minimum and maximum date now, for time it happens soon! ;)
