### ISSUE TITLE
How To Get Current Selected Date and Time as String?

### ISSUE THREAD

**Issue by MuhammadFaisalIchal** [Kunzisoft/Android-SwitchDateTimePicker#51]
I want to get the current selected date time as a string, but how to do it?
Thanks

**Comment by J-Jamet** [comment]
See sample https://github.com/Kunzisoft/Android-SwitchDateTimePicker/blob/master/sample/src/main/java/com/kunzisoft/switchdatetimesample/Sample.java
https://docs.oracle.com/javase/7/docs/api/java/text/DateFormat.html#format(java.util.Date)
