### ISSUE TITLE
Possible to define to start with cal or time?

### ISSUE THREAD

**Issue by Rainer-Lang** [Kunzisoft/Android-SwitchDateTimePicker#6]

**Comment by Rainer-Lang** [comment]
I think I should explain it....
When opening the picker, would it be possible to define if it's started with calendar or time picker?

**Comment by J-Jamet** [comment]
I'll do it in the week ;) I note all the features and bugs to resolve for the next version. For you what's the best way to init dialog as calendar ? In the getInstance or with a method after instance ? I think I will redo the initialization system for it to be simpler.

**Comment by Rainer-Lang** [comment]
About "init": I have no preference. I think more flexible could be a method after instance. But it's up to you, of course. :)

**Comment by J-Jamet** [comment]
For launch Dialog with a specific view, call : dateTimeFragment.startAtTimeView();, dateTimeFragment.startAtCalendarView(); or dateTimeFragment.startAtYearView(); before the "show" ;)
